INT_PTR CALLBACK About(HWND, UINT, WPARAM, LPARAM);
INT_PTR CALLBACK Settings(HWND, UINT, WPARAM, LPARAM);
INT_PTR CALLBACK EventLog(HWND, UINT, WPARAM, LPARAM);
INT_PTR CALLBACK MainForm(HWND, UINT, WPARAM, LPARAM);